# Generated by Django 3.1.7 on 2021-04-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_user', 'Удаление или добавление')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
