# Generated by Django 3.1.7 on 2021-03-18 10:15

from django.db import migrations, models
import webapp.validator


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210315_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.validator.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=300, validators=[webapp.validator.MinLengthValidator(5)]),
        ),
    ]
