# Generated by Django 3.1.7 on 2021-03-27 15:01

from django.db import migrations, models
import webapp.validator


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210318_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateField()),
                ('timefinish', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=300, validators=[webapp.validator.MinLengthValidator(4)])),
                ('description', models.TextField(max_length=3000, validators=[webapp.validator.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
    ]
