# Generated by Django 3.1.7 on 2021-04-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('user_add_or_del', 'Удаление или добавление')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
